"""
Rotating pool of short 'today I'm thinking about' journal entries.
update.py picks one deterministically based on the date, so the
site gets a genuinely new line each day without repeating for months.
Edit this list freely -- swap in your own TILs, links, or notes.
"""

ENTRIES = [
    "Finally understood why closures capture variables by reference, not value.",
    "Spent an hour debugging a typo in an env var name. Classic.",
    "Reading about CRDTs -- conflict-free replicated data types are wild.",
    "TIL: `git commit --fixup` + `git rebase --autosquash` is a nicer workflow than I expected.",
    "Refactored a function from 80 lines to 20. Same output, way less regret.",
    "Trying out a new terminal font. Small joys.",
    "Watched a talk on database indexing -- B-trees really do hold everything together.",
    "Wrote a test before the code for once. It caught a bug immediately.",
    "Learned the difference between `PUT` and `PATCH` the hard way.",
    "Today's win: deleted more code than I wrote.",
    "Experimenting with keyboard-only workflows. My mouse is jealous.",
    "Read up on how DNS propagation actually works end to end.",
    "Docker layer caching finally clicked for me today.",
    "Rubber-ducked a bug to my cat. She was unimpressed but it worked.",
    "Learned about idempotency keys in payment APIs -- such a clean idea.",
    "Started sketching out a side project. No promises on when it ships.",
    "Today I appreciated good error messages. Shoutout to whoever wrote that one.",
    "Explored WebAssembly for the first time. Faster than I expected to get running.",
    "Reminder to self: read the docs before Stack Overflow. Sometimes it's faster.",
    "Cleaned up a messy CSS file. Flexbox saves the day again.",
    "Learned what a bloom filter is and now I want to use one everywhere.",
    "Paired with a teammate on a tricky race condition. Two heads really did help.",
    "Today's rabbit hole: how CDNs decide which edge node serves you.",
    "Wrote a small CLI tool to automate something I do weekly. Worth it.",
    "Revisited Big-O notation while reviewing a PR. Still useful after all these years.",
    "Learned that `EXPLAIN ANALYZE` is a database's way of showing its work.",
    "Tried timeboxing my debugging sessions. Helped me step back and think clearer.",
    "Read about the CAP theorem again -- it never stops being relevant.",
    "Today I let a linter yell at me until my code was actually clean.",
    "Discovered a neat regex trick for parsing log files.",
    "Spent some time on accessibility -- alt text matters more than people think.",
    "Learned the real difference between authentication and authorization today.",
    "Today's small joy: a green CI pipeline on the first try.",
    "Read about event sourcing as an alternative to plain CRUD.",
    "Practiced explaining a technical concept in plain English. Harder than coding it.",
    "Today I appreciated semantic versioning. Rules that actually save headaches.",
    "Explored feature flags for shipping code safely. Small change, big confidence boost.",
    "Learned how load balancers decide where to route traffic.",
    "Today's takeaway: a good README saves future-me so much time.",
    "Tinkered with cron expressions until they finally did what I meant.",
    "Read about the difference between horizontal and vertical scaling.",
    "Today I fixed a bug that only happened in one specific timezone. Fun times.",
    "Learned about optimistic vs pessimistic locking in databases.",
    "Spent time thinking about naming things. The hardest problem, as always.",
    "Today's curiosity: how git actually stores objects under the hood.",
    "Read up on rate limiting strategies -- token buckets are elegant.",
    "Practiced writing commit messages that explain *why*, not just *what*.",
    "Learned how service workers make offline-first apps possible.",
    "Today I appreciated a well-designed API. Consistency really is a feature.",
    "Explored GraphQL vs REST tradeoffs for a hypothetical project.",
    "Read about how browsers parse and render HTML step by step.",
    "Today's win: caught a bug in code review before it shipped.",
    "Learned about the actor model for concurrency. Different way of thinking.",
    "Spent time organizing notes from the last few weeks. Overdue but satisfying.",
    "Today I appreciated version control history -- past me left good breadcrumbs.",
    "Read about eventual consistency in distributed systems.",
    "Practiced a coding problem just for fun, no deadline attached.",
    "Learned how content security policies help prevent XSS attacks.",
    "Today's small experiment: measuring page load time before optimizing anything.",
    "Read about the tradeoffs between monoliths and microservices, yet again.",
]
